base:
    seed: &seed 42
model:
    type: Qwen2
    path: /nfs/FM/chenshuailin/checkpoints/Qwen/Qwen2.5-3B-Instruct/
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 4
        symmetric: True
        quant_type: nvfp4
        granularity: per_group
        group_size: 16
        share_global_scale: True
    # act:
    #     bit: 8
    #     symmetric: True
    #     granularity: per_token
    special:
        rotate_mode: hadamard
        online_rotate: True
        fp32_had: True
save:
    save_trans: True
    save_fake: False
    save_vllm_nvfp4: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/quarot/nvfp4_w4a16_sgs_olrotate
dispatch:
    num_gpus: 1