base:
    seed: &seed 0
model:
    type: Qwen2
    path: /ms/FM/chenshuailin/projects/quant/OSTQuant/output/qwen3-kltop-w4a8-no_qk_smooth-seq2k-bs16/before_gptq
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: data/wikitext2
    n_samples: 64
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
quant:
    method: GPTQv2
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.05
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        online_rotate: True
        fp32_had: True
        online_rotate_exclude: ["o_proj"]
        v2_alpha: 0
    quant_out: True
save:
    save_trans: False
    save_fake: False
    save_vllm: True
    save_path: /ms/FM/chenshuailin/projects/quant/OSTQuant/output/qwen3-kltop-w4a8-no_qk_smooth-seq2k-bs16/llmc_gptqv2_debug
dispatch:
    num_gpus: 1
    # first_gpu_extra_margin: 0.05