base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/chenshuailin/checkpoints/Qwen/Qwen2.5-3B-Instruct
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: data/pileval
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: pileval_awq
    seed: *seed
# eval:
#     eval_pos: [fake_quant]
#     name: [wikitext2, c4]
#     download: False
#     path: ../cache/data/eval
#     bs: 1
#     inference_per_block: False
#     seq_len: 2048
#     tasks: piqa,arc_easy,arc_challenge,hellaswag,winogrande
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: False
        granularity: per_channel
        # group_size: 64
        calib_algo: learnable
        pack_version: gemm_pack
    special:
        trans: True
        trans_version: v2
        weight_clip: True
        clip_sym: True
save:
    save_trans: true
    # save_fake: True
    save_autoawq: True
    # save_vllm: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/awq/w4a16_asym
dispatch:
    num_gpus: 1
    # safe_margin: 0.5