base:
    seed: &seed 0
model:
    type: Qwen2
    path: checkpoints/Qwen3-0.6B/quarot/sym_w4_a8-dynamic/transformed_model
    torch_dtype: auto
calib:
    name: wikitext2
    preproc: wikitext2_gptq
    path: data/wikitext2
    download: False
    n_samples: 128
    bs: 1
    seq_len: 2048
    seed: *seed
quant:
    method: GPTQv2
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        calib_algo: mse
    # act:
    #     bit: 8
    #     symmetric: True
    #     granularity: per_token
    #     calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.05
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        online_rotate: False
        fp32_had: True
        # online_rotate_exclude: ["o_proj"]
    quant_out: True
save:
    save_trans: False
    save_fake: False
    save_vllm: True
    save_path: checkpoints/Qwen3-0.6B/gptqv2/quarot_gptqv2_w4a16_sym
dispatch:
    num_gpus: 1