base:
    seed: &seed 42
model:
    type: Llama
    path: /nfs/FM/chenshuailin/checkpoints/LLM-Research/Meta-Llama-3___1-8B-Instruct
    torch_dtype: torch.bfloat16
calib:
    name: wikitext2
    preproc: wikitext2_gptq
    path: data/wikitext2
    download: False
    n_samples: 128
    bs: 1
    seq_len: 2048
    seed: *seed
quant:
    method: GPTQ
    weight:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
        # calib_algo: mse
    act:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
        calib_algo: static_minmax
        static: True
    special:
        actorder: True
        static_groups: True
        percdamp: 0.05
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        online_rotate: False
        fp32_had: True
        # online_rotate_exclude: ["o_proj"]
        eager_transform_dtype: False
        force_scale_dtype: False
    quant_out: True
save:
    # save_fake: True
    # save_vllm: True
    # save_autoawq: True
    save_vllm_nvfp4: True
    save_path: checkpoints/llama3.1-8B-it/gptq/nvfp4_w4a4_sgs
dispatch:
    num_gpus: 1
    first_gpu_extra_margin: 0.1