base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/chenshuailin/checkpoints/Qwen/Qwen2.5-7B-Instruct/
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 64
        pack_version: gemm_pack
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: False
        # weight_clip: True
        # clip_sym: False
save:
    # save_fake: True
    # save_trans: True
    # save_vllm: True
    save_autoawq: True
    save_path: /data/chenshuailin/checkpoints/llmc/Qwen2.5-7B-Instruct/quarot/asym_w4a16
dispatch:
    first_gpu_extra_margin: 0.8
    safe_margin: 0.9
