base:
    seed: &seed 42
model:
    type: DeepseekV3
    path: /data/chenshuailin/checkpoints/deepseek-ai/DeepSeek-R1-bf16
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: True
save:
    save_fake: True
    # save_trans: True
    # save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/DeepSeek-R1/quarot/sym_w8a8_dynamic
dispatch:
    first_gpu_extra_margin: 0.8
    safe_margin: 0.9
