base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/chenshuailin/checkpoints/Qwen/Qwen3-1.7B
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        round_func: stochastic
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: False
save:
    save_trans: True
    save_fake: True
    save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/Qwen3-1.7B/quarot/stochastic_round_sym_w4_a8-dynamic
dispatch:
    num_gpus: 1