base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/chenshuailin/checkpoints/Qwen/Qwen3-32B
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: False
save:
    save_trans: True
    save_fake: True
    save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/Qwen3-32B/quarot/sym_w8_a8-dynamic
dispatch:
    first_gpu_extra_margin: 0.5
    safe_margin: 0.8