base:
    seed: &seed 0
model:
    type: Qwen3MOE
    path: checkpoints/Qwen3-30B-A3B-Instruct-2507/quarot/sym_w4a8/transformed_model
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: data/wikitext2
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        # group_size: 64
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        online_rotate: False
        fp32_had: True
    quant_out: True
save:
    # save_trans: True
    save_fake: True
    save_vllm: True
    save_path: checkpoints/Qwen3-30B-A3B-Instruct-2507/gptq/quarot_gptq_sym_w4a8
dispatch:
    first_gpu_extra_margin: 0.6
    safe_margin: 0.8
    num_gpus: 4