base:
    seed: &seed 42
model:
    type: DeepseekV2
    path: /data/chenshuailin/checkpoints/deepseek-ai/DeepSeek-V2.5-1210
    # type: Qwen2
    # path: /data/chenshuailin/checkpoints/Qwen/Qwen2.5-7B-Instruct/
    # path: /data/chenshuailin/checkpoints/Qwen/Qwen2.5-32B-Instruct
    # path: /data/chenshuailin/checkpoints/Qwen/Qwen2.5-72B-Instruct
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
calib:
    name: pileval
    download: False
    path: data/pileval
    n_samples: 256
    bs: 1
    seq_len: 4096
    preproc: txt_general_preproc
    seed: *seed
quant:
    method: SmoothQuant
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        alpha: 0.8
save:
    save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/DeepSeek-V2.5-sq-sym_w8a8-dynamic
