base:
    seed: &seed 42
model:
    type: Qwen2
    path: /nfs/FM/chenshuailin/checkpoints/Qwen/Qwen2.5-3B-Instruct/
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
calib:
    name: pileval
    download: False
    path: data/pileval
    n_samples: 128
    bs: 1
    seq_len: 1024
    preproc: txt_general_preproc
    seed: *seed
quant:
    method: SmoothQuant
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_tensor
        static: True
        calib_algo: static_minmax
        # calib_algo: static_hist
    special:
        alpha: 0.8
save:
    save_vllm: True
    # save_trans: True
    # save_fake: True
    save_path: /data/chenshuailin/checkpoints/llmc/DeepSeek-V3-1B-Test/smoothquant/sym_w8-per-channel_a8-per-tensor-static
dispatch:
    first_gpu_extra_margin: 0.8
    safe_margin: 0.8
