base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/chenshuailin/checkpoints/Qwen/Qwen3-0.6B
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
save:
    save_fake: True
    save_vllm: True
    save_path: checkpoints/Qwen3-0.6B/rtn/sym_w4g128
dispatch:
    num_gpus: 1