base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/chenshuailin/checkpoints/Qwen/Qwen2.5-3B-Instruct/
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
save:
    save_fake: True
    save_vllm: True
    # save_autoawq: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/RTN/sym_w4a16
dispatch:
    num_gpus: 1