base:
    seed: &seed 0
model:
    type: DeepseekV3
    # Load Quarot-transformed model
    path: checkpoints/DeepSeek-R1/quarot/sym_w8a8-dynamic_ol-rotate/transformed_model
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
calib:
    name: pileval
    download: False
    path: data/pileval
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: txt_general_preproc
    seed: *seed
# eval:
#     eval_pos: [fake_quant]
#     name: wikitext2
#     download: False
#     path: eval data path
#     seq_len: 2048
#     # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
#     # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
#     bs: 1
#     inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        # group_size: -1
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_tensor
        static: True
        calib_algo: static_minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        chunk_num: 4
        true_sequential: True
        online_rotate: True
        fp32_had: True
    quant_out: True
save:
    save_trans: False
    save_fake: False
    save_path: checkpoints/DeepSeek-R1/gptq/sym_w8a8-static_ol-rotate
