base:
    seed: &seed 42
model:
    type: DeepseekV2
    path: /data/chenshuailin/checkpoints/deepseek-ai/DeepSeek-V2-Lite
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: True
save:
    save_trans: True
    save_fake: True
    save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/DeepSeek-V2-Lite/quarot/sym_w8_a8-dynamic_ol-rotate
dispatch:
    num_gpus: 4
    first_gpu_extra_margin: 0.8
    safe_margin: 0.9