base:
    seed: &seed 0
model:
    type: Qwen2
    path: checkpoints/Qwen3-0.6B/quarot/sym_w8_a8-dynamic_ol-rotate/transformed_model
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: data/wikitext2
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: False
        granularity: per_channel
        # group_size: 64
        calib_algo: mse
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        chunk_num: 4
        true_sequential: True
        online_rotate: True
        fp32_had: True
    quant_out: True
save:
    save_fake: True
    save_trans: True
    save_vllm: True
    save_path: checkpoints/Qwen3-0.6B/gptq/quarot_ol_rotate_gptq_w4a16_asym
dispatch:
    num_gpus: 1