base:
    seed: &seed 0
model:
    type: Qwen2
    path: /ms/FM/wuwenxian/project/quant/OSTQuant/translate/Qwen3-32B_w4a8_no-qk-smooth_no-Rov-seq2k/before_gptq
    torch_dtype: torch.float16
calib:
    name: wikitext2
    path: data/wikitext2
    preproc: wikitext2_gptq
    download: False
    n_samples: 128
    bs: 1
    seq_len: 2048
    seed: *seed
quant:
    method: GPTQv2
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.05
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        online_rotate: True
        fp32_had: True
        online_rotate_exclude: ["o_proj"]
        eager_transform_dtype: True
        force_scale_dtype: True
    quant_out: True
save:
    # save_trans: True
    # save_fake: True
    save_vllm: True
    save_path: /ms/FM/wuwenxian/project/quant/OSTQuant/translate/Qwen3-32B_w4a8_no-qk-smooth_no-Rov-seq2k/after_gptqv2
dispatch:
    num_gpus: 2
    first_gpu_extra_margin: 0.5