base:
    seed: &seed 0
model:
    type: Qwen2
    path: checkpoints/Qwen2.5-3B-Instruct/quarot/sym_w4a8-dynamic_ol-rotate/transformed_model
    torch_dtype: torch.float32
calib:
    name: wikitext2
    download: False
    path: data/wikitext2
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
quant:
    method: GPTQv2
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.05
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        online_rotate: True
        fp32_had: True
    quant_out: True
save:
    # save_trans: True
    # save_fake: True
    save_vllm: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/gptqv2/sym_w4a8_olrotate_fp32
dispatch:
    num_gpus: 1