base:
    seed: &seed 0
model:
    type: Qwen2
    path: /nfs/FM/chenshuailin/checkpoints/Qwen/Qwen3-0.6B
    # path: /nfs/FM/chenshuailin/checkpoints/Qwen/Qwen2.5-3B-Instruct/
    torch_dtype: torch.bfloat16
calib:
    name: wikitext2
    preproc: wikitext2_gptq
    path: data/wikitext2
    download: False
    n_samples: 8
    bs: 1
    seq_len: 128
    seed: *seed
quant:
    method: GPTQv2
    weight:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
        # calib_algo: mse
    act:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
        calib_algo: static_minmax
        static: True
    special:
        actorder: True
        static_groups: True
        percdamp: 0.05
        blocksize: 128
        chunk_num: 1
        true_sequential: True
        # online_rotate: True
        fp32_had: False
        # online_rotate_exclude: ["o_proj"]
        eager_transform_dtype: True
        force_scale_dtype: True
    quant_out: True
save:
    save_trans: False
    save_fake: False
    save_vllm_nvfp4: True
    save_path: checkpoints/debug
dispatch:
    num_gpus: 1