base:
    seed: &seed 0
model:
    type: DeepSeekV2
    path: /data/chenshuailin/checkpoints/deepseek-ai/DeepSeek-V2-Lite
    torch_dtype: auto
calib:
    name: pileval
    download: False
    n_samples: 128
    path: data/pileval
    bs: 1
    seq_len: 2048
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: data/wikitext2
    bs: 1
    seq_len: 2048
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 8
        symmetric: True
        granularity: per_group
        group_size: -1
        calib_algo: mse
        # mse_b_num: 2
    act:
        bit: 8
        symmetric: False
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: False
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
        fp32_had: True
    quant_out: True
save:
    save_trans: True
    save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/DeepSeek-V2-Lite/gptq/pileval_n128_s2k_sym_w8a8_dynamic
