base:
    seed: &seed 42
model:
    type: DeepseekV3
    path: /data/chenshuailin/checkpoints/deepseek-ai/DeepSeek-R1-bf16
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: False
        granularity: per_channel
    act:
        bit: 8
        symmetric: False
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: False
save:
    save_trans: True
    save_vllm: True
    save_path: /data/chenshuailin/checkpoints/llmc/DeepSeek-R1-quarot-dynamic
